import io
import zipfile

from services.jira_service import (
    JiraAttachment,
    JiraBoard,
    JiraComment,
    JiraIssue,
    JiraIssueRef,
    _attach_reverse_children,
    _extract_docx_text,
    _extract_xlsx_text,
    _issue_metadata,
    _render_issue_markdown,
    adf_to_text,
)


def test_jira_issue_rendering_indexes_assignment_and_status_fields() -> None:
    board = JiraBoard(id=154, name="DevOps Dashboard", type="kanban", url="https://example.test/board")
    issue = JiraIssue(
        id="10555",
        key="DEVO-10555",
        title="Broker installation",
        url="https://example.test/browse/DEVO-10555",
        issue_type="Task",
        status="To Do",
        status_category="To Do",
        status_category_key="new",
        priority="Medium",
        labels=[],
        components=[],
        assignee="Shivam Kumar",
        assignee_email="s.kumar@kimbal.io",
        assignee_account_id="abc-123",
        reporter="Platform",
        reporter_email="platform@kimbal.io",
        reporter_account_id="reporter-123",
        created_at="2026-07-04T00:00:00.000+0000",
        updated_at="2026-07-04T01:00:00.000+0000",
        description="Install the broker service.",
        project_key="DEVO",
        project_name="DevOps",
    )

    rendered = _render_issue_markdown(board=board, issue=issue)
    metadata = _issue_metadata(board=board, issue=issue)

    assert "Assignee:** Shivam Kumar" in rendered
    assert "s.kumar@kimbal.io" not in rendered
    assert "abc-123" not in rendered
    assert metadata["jira_assignee_email"] == "s.kumar@kimbal.io"
    assert metadata["jira_issue_status_category_key"] == "new"
    assert metadata["source"] == "jira"
    assert metadata["source_type"] == "jira"
    assert metadata["project"] == "DEVO"
    assert metadata["issue_key"] == "DEVO-10555"
    assert metadata["title"] == "DEVO-10555: Broker installation"
    assert metadata["url"] == "https://example.test/browse/DEVO-10555"
    assert metadata["updated_at"] == "2026-07-04T01:00:00.000+0000"
    assert metadata["source_updated_at"] == "2026-07-04T01:00:00.000+0000"
    assert metadata["status"] == "To Do"
    assert metadata["labels"] == []
    assert metadata["owner"] == "s.kumar@kimbal.io"
    assert metadata["acl"] == "connector-visible"
    assert metadata["connector_sync_id"] == "jira:DEVO:DEVO-10555:2026-07-04T01:00:00.000+0000"
    assert metadata["chunk_strategy_version"] == "jira-relationship-comments-attachments-v5"


def test_jira_adf_preserves_structure_and_removes_automation_noise() -> None:
    rendered = adf_to_text(
        {
            "type": "doc",
            "content": [
                {"type": "heading", "attrs": {"level": 2}, "content": [{"type": "text", "text": "Resolution"}]},
                {"type": "paragraph", "content": [{"type": "text", "text": "Restart the broker."}]},
                {"type": "paragraph", "content": [{"type": "text", "text": "Generated by Jira automation"}]},
                {
                    "type": "bulletList",
                    "content": [
                        {
                            "type": "listItem",
                            "content": [
                                {
                                    "type": "paragraph",
                                    "content": [{"type": "text", "text": "Verify health"}],
                                }
                            ],
                        }
                    ],
                },
            ],
        }
    )

    assert "## Resolution" in rendered
    assert "- Verify health" in rendered
    assert "automation" not in rendered.lower()


def test_jira_relationship_comments_and_attachment_evidence_are_rendered() -> None:
    board = JiraBoard(id=154, name="DevOps", type="kanban", url="https://example.test/board")
    epic = _issue(key="DEVO-9195", title="EHES PoC with OCI", issue_type="Epic")
    child = _issue(
        key="DEVO-9293",
        title="Verify OCI Terraform, Architecture and Infra",
        parent=JiraIssueRef(key=epic.key, title=epic.title, relationship="parent"),
        comments=(
            JiraComment(
                id="1",
                author="Shivam Kumar",
                body="Benchmark result: VM.Standard.E4.Flex, 16 OCPU and 128 GB RAM.",
                created_at="2026-04-01T10:00:00Z",
                updated_at=None,
            ),
        ),
        attachments=(
            JiraAttachment(
                id="10",
                filename="oci-benchmark.xlsx",
                mime_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                size_bytes=2048,
                content_url="https://example.test/attachment/10",
                created_at="2026-04-01T10:00:00Z",
                author="Shivam Kumar",
                extracted_text="Shape | OCPU | RAM\nVM.Standard.E4.Flex | 16 | 128 GB",
            ),
        ),
    )
    enriched_epic = _attach_reverse_children([epic, child])[0]

    assert enriched_epic.child_issues[0].key == "DEVO-9293"
    rendered = _render_issue_markdown(board=board, issue=child)
    assert "Parent epic/issue:** DEVO-9195" in rendered
    assert "Benchmark result" in rendered
    assert "oci-benchmark.xlsx" in rendered
    assert "VM.Standard.E4.Flex | 16 | 128 GB" in rendered


def test_jira_rendering_removes_database_invalid_nul_bytes() -> None:
    board = JiraBoard(id=154, name="DevOps", type="kanban", url="https://example.test/board")
    issue = _issue(
        key="DEVO-1888",
        title="Terraform analysis",
        comments=(
            JiraComment(
                id="1",
                author="Shivam Kumar",
                body="Scanner output before\x00after",
                created_at="2026-04-01T10:00:00Z",
                updated_at=None,
            ),
        ),
    )

    rendered = _render_issue_markdown(board=board, issue=issue)
    assert "\x00" not in rendered
    assert "beforeafter" in rendered


def test_xlsx_attachment_extraction_preserves_server_cells() -> None:
    payload = io.BytesIO()
    with zipfile.ZipFile(payload, "w") as workbook:
        workbook.writestr(
            "xl/sharedStrings.xml",
            '<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
            "<si><t>Instance Type</t></si><si><t>VM.Standard.E4.Flex</t></si><si><t>RAM</t></si>"
            "</sst>",
        )
        workbook.writestr(
            "xl/worksheets/sheet1.xml",
            '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'
            '<row><c t="s"><v>0</v></c><c t="s"><v>2</v></c></row>'
            '<row><c t="s"><v>1</v></c><c><v>128</v></c></row>'
            "</sheetData></worksheet>",
        )

    extracted = _extract_xlsx_text(payload.getvalue())
    assert "Instance Type | RAM" in extracted
    assert "VM.Standard.E4.Flex | 128" in extracted


def test_docx_attachment_extraction_preserves_load_test_tables() -> None:
    from docx import Document as WordDocument

    payload = io.BytesIO()
    document = WordDocument()
    document.add_heading("AWS vs OCI load test", level=1)
    table = document.add_table(rows=2, cols=3)
    table.rows[0].cells[0].text = "Cloud"
    table.rows[0].cells[1].text = "OCPU"
    table.rows[0].cells[2].text = "RAM"
    table.rows[1].cells[0].text = "OCI VM.Standard.E6"
    table.rows[1].cells[1].text = "2"
    table.rows[1].cells[2].text = "8 GB"
    document.save(payload)

    extracted = _extract_docx_text(payload.getvalue())
    assert "AWS vs OCI load test" in extracted
    assert "OCI VM.Standard.E6 | 2 | 8 GB" in extracted


def _issue(
    *,
    key: str,
    title: str,
    issue_type: str = "Task",
    parent: JiraIssueRef | None = None,
    comments: tuple[JiraComment, ...] = (),
    attachments: tuple[JiraAttachment, ...] = (),
) -> JiraIssue:
    issue = JiraIssue(
        id=key.split("-")[-1],
        key=key,
        title=title,
        url=f"https://example.test/browse/{key}",
        issue_type=issue_type,
        status="Done",
        status_category="Done",
        status_category_key="done",
        priority="Medium",
        labels=[],
        components=[],
        assignee="Shivam Kumar",
        assignee_email="s.kumar@example.test",
        assignee_account_id="account",
        reporter="Shivam Kumar",
        reporter_email="s.kumar@example.test",
        reporter_account_id="account",
        created_at="2026-03-26T00:00:00Z",
        updated_at="2026-04-01T00:00:00Z",
        description="",
        project_key="DEVO",
        project_name="DevOps",
        parent=parent,
        comments=comments,
        attachments=attachments,
    )
    return issue
